# WARNING change the title in content/_index.md too
title = "The Unofficial Directory — Government of India"

# The URL the site will be built for
base_url = "https://arunkd13.github.io/directory-gov-in"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

taxonomies = [
    {name = "maintenance"},
    {name = "adviser"},
    {name = "during_the_pleasure_of"},
    {name = "head"},
    {name = "member_of"},
    {name = "responsible_to"}
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
[search]
index_format = "elasticlunr_json"
include_description = true
include_path = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

generate_feeds = false

[extra]
# Put all your custom variables here
source = "https://github.com/arunkd13/directory-gov-in"

[extra.contact.icons]
phone = "fa-solid fa-phone"
website = "fa-solid fa-globe"
wikipedia = "fa-brands fa-wikipedia-w"
x = "fa-brands fa-x-twitter"
facebook = "fa-brands fa-facebook"
instagram = "fa-brands fa-instagram"
youtube = "fa-brands fa-youtube"

[extra.link.labels]
adviser = "Adviser"
during_the_pleasure_of = "During the pleasure of"
head = "Head"
member_of = "Member of"
responsible_to = "Responsible to"

[extra.backlink.labels]
adviser = "Advises"
during_the_pleasure_of = "During their pleasure"
head = "Heads"
member_of = "Members"
responsible_to = "Under their responsibility"