# The URL the site will be built for
base_url = "https://arunkd13.github.io/directory-india-gov"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

taxonomies = [
    {name = "adviser"},
    {name = "during_the_pleasure_of"},
    {name = "head"},
    {name = "member_of"},
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
[search]
index_format = "elasticlunr_json"
include_description = true
include_path = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

generate_feeds = false

[extra]
# Put all your custom variables here

[extra.link.labels]
adviser = "Adviser"
during_the_pleasure_of = "During the pleasure of"
head = "Head"
member_of = "Member of"

[extra.backlink.labels]
adviser = "Advises"
during_the_pleasure_of = "During their pleasure"
head = "Heads"
member_of = "Members"